version: '3.3'
networks:
  resource:
    attachable: true
services:
  thoregon:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: resourceserver
    restart: unless-stopped
    volumes:
      - /home/lucky/containers/resourceserver/www:/resources/www
    networks:
      - resource
    ports:
      - 7779:7779
